# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jps_gallery_tools',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/jps_gallery_tools',
                'lib_path': 'jps_gallery_tools'},
  'syms': { 'jps_gallery_tools.api': { 'jps_gallery_tools.api.JPSGalleryClient': ('api.html#jpsgalleryclient', 'jps_gallery_tools/api.py'),
                                       'jps_gallery_tools.api.JPSGalleryClient.__init__': ( 'api.html#jpsgalleryclient.__init__',
                                                                                            'jps_gallery_tools/api.py'),
                                       'jps_gallery_tools.api.JPSGalleryClient.show': ( 'api.html#jpsgalleryclient.show',
                                                                                        'jps_gallery_tools/api.py')},
            'jps_gallery_tools.core': { 'jps_gallery_tools.core.bar': ('core.html#bar', 'jps_gallery_tools/core.py'),
                                        'jps_gallery_tools.core.foo': ('core.html#foo', 'jps_gallery_tools/core.py'),
                                        'jps_gallery_tools.core.say_hello': ('core.html#say_hello', 'jps_gallery_tools/core.py')}}}