# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jps_gallery_tools',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/jps_gallery_tools',
                'lib_path': 'jps_gallery_tools'},
  'syms': {'jps_gallery_tools.core': {'jps_gallery_tools.core.foo': ('core.html#foo', 'jps_gallery_tools/core.py')}}}