# AUTOGENERATED! DO NOT EDIT! File to edit: ../api.ipynb.

# %% auto 0
__all__ = ['JPSGalleryClient']

# %% ../api.ipynb 3
from pprint import pprint
class JPSGalleryClient(object):
    def __init__(self, api_url, key_identity=None, key_credential=None, use_cache=True):
        self.api_url = api_url
        self.params = {
            'key_identity': key_identity,
            'key_credential': key_credential
        }

    def show(self):
        pprint(self.params)
